### PR TITLE
fix(view, viewmodel, service): use full file name as file identifier

### LINKED ISSUE #1582: Error thrown when accessing React challenges
## Description

I'm getting the following error when accessing a React challenge:

```
The following assertion was thrown building Consumer<ChallengeViewModel>(dirty, dependencies:
[_InheritedProviderScope<ChallengeViewModel?>]):
There should be exactly one item with [DropdownButton]'s value: index.
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 1001 pos 10: 'items == null ||
             items.isEmpty ||
             value == null ||
             items.where((DropdownMenuItem<T> item) {
                   return item.value == value;
                 }).length ==
                 1'
```

The issue is reproducible in both lab and workshop challenges.

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of the repo.
- [x] I have tested these changes locally on my machine.

This PR:
- Updates the file identifier to be `[fileName].[fileExtension]` instead of just file name. This is to ensure the uniqueness as React challenges can have both `index.jsx` and `index.html`
- Closes #1582 

## Testing

I've tested and verified the following cases:
- React coding challenges are now accessible, file selection drowdown displays correctly
    <details>
      <summary>Screenshot</summary>
         
    Screenshot 2025-07-03 at 17 38 34

    </details>
- Challenge reset is working as expected
- The file content are saved and retrieved correctly as expected
- Tests run on HTML, CSS, JS challenges correctly as expected

## But...

The tests fail on React challenges. It seems the user's code isn't passed to the tests. The tests can't see the code change and just run against the seed code.

I'm not sure if this is related to the test runner integration or if I'm missing something obvious.

Feel free to push changes to the PR to speed things up.

### CODE REVIEW

File: mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart [hunk 1]
```diff
@@ -567,8 +571,8 @@ class ChallengeViewModel extends BaseViewModel {
       Challenge? currChallenge = challenge;
 
       for (ChallengeFile file in currChallenge!.files) {
-        await prefs.remove('${currChallenge.id}.${file.name}');
-        await prefs.remove('${currChallenge.id}${file.name}');
+        await prefs.remove('${currChallenge.id}.${getFullFileName(file)}');
+        await prefs.remove('${currChallenge.id}${getFullFileName(file)}');
```
Comment (Nirajn2311) [inline mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart:575]: Uhhhh 🤔

Comment (Sembauke) [reply mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart:575]: I think that might be some kind of artifact. Not sure.

**Review by Sembauke — APPROVED** [review]

File: mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart (hunk 1 above)
Comment (Nirajn2311) [reply mobile-app/lib/ui/views/learn/challenge/challenge_viewmodel.dart]: We need to check and remove it if there's no preference with that key
