### PR TITLE
fix(view): challenge title

### LINKED ISSUE #1525: FSD lecture titles are not correct
## Description

The title is currently showing the number of the lecture within the block ("2 of 4", "3 of 4", etc.). I'm not sure if this is intended.

<details>

<summary>Screenshot</summary>

Image

</details>

Note that the lecture view is currently broken. It will be fixed by #1524.

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of the repo.
- [x] I have tested these changes locally on my machine.

Closes #1525

The easiest change to address the issue would be removing the appBar title entirely. But I'm trying out an alternative solution, so this PR is more of a proposal than a final fix. Inputs are appreciated.

## Screenshots

<details>
<summary>English view - Dialogue</summary>

Screenshot 2025-06-13 at 14 35 12

</details>

<details>
<summary>English view - Task</summary>

For this view, we already have a ChallengeCard with the description and the "Task X" title, and it now looks redundant as we have the appBar title. ChallengeCard requires a title, so I'm considering replacing "Task X" with just "Description".

Though this would cause an inconsistency in the ChallengeCard title:
- Dialogue challenges will have ChallengeCard title as the challenge title
- Task challenges will have ChallengeCard title as "Description"

Screenshot 2025-06-13 at 14 21 56

</details>

<details>
<summary>MCQ view</summary>

Screenshot 2025-06-13 at 14 22 54

</details>

<details>
<summary>Python view</summary>

Screenshot 2025-06-13 at 14 23 54

</details>

<details>
<summary>Review view</summary>

Screenshot 2025-06-12 at 01 28 01

</details>

### CODE REVIEW

File: mobile-app/lib/ui/views/learn/utils/challenge_utils.dart [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+  }
+
+  int numberOfDialogueHeaders = block.challenges
+      .where((challenge) => challenge.title.contains('Dialogue'))
+      .length;
+
+  // English challenges have titles like "Task 1", "Task 2", etc.
+  // The number of tasks = total challenges - number of dialogue headers
+  if (challenge.title.contains('Task')) {
+    return '${challenge.title} of ${block.challenges.length - numberOfDialogueHeaders}';
```
Comment (Sembauke) [inline mobile-app/lib/ui/views/learn/utils/challenge_utils.dart:16]: Should Task be part of the title?

**Review by Nirajn2311 — APPROVED** [review]
LGTM
